export type LessonMeta = {
  id: string;
  title: string;
  lessonUnits: string;
  blockTitle: string;
  year: 10 | 11;
  block: string;
};

export type YearBlock = {
  block: string;
  blockTitle: string;
  lessons: LessonMeta[];
};

export type SubjectCurriculum = {
  label: string;
  examBoard: string;
  lessonsPerWeek: number;
  lessons: LessonMeta[];
  byYear: { year10: YearBlock[]; year11: YearBlock[] };
};

export const CURRICULUM: Record<"english" | "maths", SubjectCurriculum> = {
  english: {
    label: "English Language & Literature",
    examBoard: "AQA",
    lessonsPerWeek: 3,
    lessons: [
      { id: "english.y10.l01-03", title: "An Inspector Calls - Context", lessonUnits: "1-3", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l04-05", title: "Act 1 - Events and Characters", lessonUnits: "4-5", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l06-07", title: "Act 2 - Themes and Development", lessonUnits: "6-7", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l08-09", title: "Act 3 - Resolution and Conclusion", lessonUnits: "8-9", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l10-11", title: "Act 3 Analysis and Key Themes", lessonUnits: "10-11", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l12", title: "Character Studies and Development", lessonUnits: "12", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l13-14", title: "Themes and Motifs", lessonUnits: "13-14", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l15", title: "Context and Exam-Style Questions", lessonUnits: "15", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l16-17", title: "Paper 1 Q5 - Descriptive Writing", lessonUnits: "16-17", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l18", title: "Sensory Details and Descriptive Planning", lessonUnits: "18", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
      { id: "english.y10.l19", title: "Anthology Introduction", lessonUnits: "19", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l20", title: "Ozymandias and London", lessonUnits: "20", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l21", title: "My Last Duchess and The Charge of the Light Brigade", lessonUnits: "21", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l22", title: "Bayonet Charge and Poppies", lessonUnits: "22", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l23", title: "Exposure and Storm on the Island", lessonUnits: "23", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l24", title: "Remains and War Photographer", lessonUnits: "24", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l25", title: "Tissue and The Emigree", lessonUnits: "25", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l26-27", title: "Comparative Analysis of Poems", lessonUnits: "26-27", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l28", title: "Contextual and Thematic Links", lessonUnits: "28", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l29-30", title: "Introduction to Unseen Poetry", lessonUnits: "29-30", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l31", title: "Techniques for Unseen Poetry", lessonUnits: "31", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l32", title: "Comparative Analysis of Unseen Poems", lessonUnits: "32", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l33", title: "Understanding Non-Fiction Forms", lessonUnits: "33", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l34", title: "Writing Speeches and Letters", lessonUnits: "34", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l35", title: "Writing Articles and Opinion Pieces", lessonUnits: "35", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l36", title: "Planning, Drafting and Final Assessment", lessonUnits: "36", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
      { id: "english.y10.l37-39", title: "Literature Revision Consolidation", lessonUnits: "37-39", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l40-42", title: "Reviewing Power and Conflict Poems", lessonUnits: "40-42", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l43-44", title: "Reviewing Unseen Poetry", lessonUnits: "43-44", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l45-46", title: "Exam Practice and Timed Essays", lessonUnits: "45-46", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l47-48", title: "Paper 1 Section A - Understanding Questions", lessonUnits: "47-48", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l49-50", title: "Reading Comprehension Strategies", lessonUnits: "49-50", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l51-52", title: "Analysing Language and Structure", lessonUnits: "51-52", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l53-54", title: "Past Paper Practice and Peer Review", lessonUnits: "53-54", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
      { id: "english.y10.l55-56", title: "Macbeth - Introduction and Context", lessonUnits: "55-56", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l57-58", title: "Macbeth Act 1 Analysis", lessonUnits: "57-58", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l59-60", title: "Macbeth Act 2 Analysis", lessonUnits: "59-60", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l61-62", title: "Macbeth Act 2 - Key Themes", lessonUnits: "61-62", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l63-64", title: "Macbeth Act 3 - Conflict Development", lessonUnits: "63-64", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l65", title: "Macbeth Act 4 - Themes and Characters", lessonUnits: "65", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l66-67", title: "Paper 2 Section A - Reading Skills", lessonUnits: "66-67", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l68-69", title: "Paper 2 - Question Types and Strategies", lessonUnits: "68-69", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l70", title: "Reading Comprehension Strategies", lessonUnits: "70", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l71", title: "Analysing Language and Structure", lessonUnits: "71", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l72", title: "Past Paper Practice", lessonUnits: "72", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
      { id: "english.y10.l73-77", title: "Macbeth and Poetry Consolidation", lessonUnits: "73-77", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l78-80", title: "Comparative Analysis - Power and Conflict", lessonUnits: "78-80", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l81-83", title: "Paper 1 and Paper 2 Writing Skills", lessonUnits: "81-83", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l84-86", title: "Creative and Viewpoint Writing", lessonUnits: "84-86", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l87-90", title: "Exam Technique and Revision", lessonUnits: "87-90", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l91-94", title: "Literature Revision - Key Texts", lessonUnits: "91-94", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l95-98", title: "Language Skills Revision", lessonUnits: "95-98", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l99-102", title: "Comparative Literature Practice", lessonUnits: "99-102", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l103-106", title: "Timed Exam Practice", lessonUnits: "103-106", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y10.l107-108", title: "End of Year Review and Consolidation", lessonUnits: "107-108", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
      { id: "english.y11.l01-02", title: "A Christmas Carol - Introduction", lessonUnits: "1-2", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l03-06", title: "Character Analysis", lessonUnits: "3-6", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l07-10", title: "Themes and Motifs", lessonUnits: "7-10", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l11-13", title: "Writer's Methods", lessonUnits: "11-13", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l14-15", title: "Essay Writing Practice", lessonUnits: "14-15", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l16", title: "Contextual Understanding", lessonUnits: "16", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l17-18", title: "Paper 2 Reading Comprehension", lessonUnits: "17-18", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l19-20", title: "Language Analysis Skills", lessonUnits: "19-20", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l21-24", title: "Comparison and Viewpoint Writing", lessonUnits: "21-24", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
      { id: "english.y11.l25-28", title: "Anthology Poems 1-5 Analysis", lessonUnits: "25-28", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
      { id: "english.y11.l29-30", title: "Unseen Poetry Analysis", lessonUnits: "29-30", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
      { id: "english.y11.l31-32", title: "Poems 6-10 and Comparison", lessonUnits: "31-32", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
      { id: "english.y11.l33-34", title: "Unseen Poetry Practice", lessonUnits: "33-34", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
      { id: "english.y11.l35", title: "Comparative Essay Writing", lessonUnits: "35", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
      { id: "english.y11.l36-38", title: "Reading Fiction Techniques", lessonUnits: "36-38", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
      { id: "english.y11.l39-43", title: "Narrative Structure Analysis", lessonUnits: "39-43", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
      { id: "english.y11.l44-46", title: "Descriptive Writing Techniques", lessonUnits: "44-46", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
      { id: "english.y11.l47-48", title: "Creative Writing Practice", lessonUnits: "47-48", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
      { id: "english.y11.l49-52", title: "Paper 1 Revision - Key Texts", lessonUnits: "49-52", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
      { id: "english.y11.l53-54", title: "Practice Papers - Paper 1", lessonUnits: "53-54", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
      { id: "english.y11.l55-60", title: "Targeted Revision", lessonUnits: "55-60", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
      { id: "english.y11.l61-62", title: "Paper 2 Revision - Key Texts", lessonUnits: "61-62", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
      { id: "english.y11.l63-64", title: "Practice Papers - Paper 2", lessonUnits: "63-64", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
      { id: "english.y11.l65", title: "Individual Targeted Revision", lessonUnits: "65", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
      { id: "english.y11.l66-69", title: "GCSE Exam Preparation", lessonUnits: "66-69", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
      { id: "english.y11.l69-72", title: "Final Practice Papers", lessonUnits: "69-72", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
    ],
    byYear: {
      year10: [
      {
        block: "inspector-paper1",
        blockTitle: "An Inspector Calls and Paper 1 Language Skills",
        lessons: [
        { id: "english.y10.l01-03", title: "An Inspector Calls - Context", lessonUnits: "1-3", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l04-05", title: "Act 1 - Events and Characters", lessonUnits: "4-5", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l06-07", title: "Act 2 - Themes and Development", lessonUnits: "6-7", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l08-09", title: "Act 3 - Resolution and Conclusion", lessonUnits: "8-9", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l10-11", title: "Act 3 Analysis and Key Themes", lessonUnits: "10-11", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l12", title: "Character Studies and Development", lessonUnits: "12", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l13-14", title: "Themes and Motifs", lessonUnits: "13-14", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l15", title: "Context and Exam-Style Questions", lessonUnits: "15", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l16-17", title: "Paper 1 Q5 - Descriptive Writing", lessonUnits: "16-17", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        { id: "english.y10.l18", title: "Sensory Details and Descriptive Planning", lessonUnits: "18", blockTitle: "An Inspector Calls and Paper 1 Language Skills", year: 10, block: "inspector-paper1" },
        ],
      },
      {
        block: "poetry",
        blockTitle: "Power and Conflict Poetry",
        lessons: [
        { id: "english.y10.l19", title: "Anthology Introduction", lessonUnits: "19", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l20", title: "Ozymandias and London", lessonUnits: "20", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l21", title: "My Last Duchess and The Charge of the Light Brigade", lessonUnits: "21", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l22", title: "Bayonet Charge and Poppies", lessonUnits: "22", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l23", title: "Exposure and Storm on the Island", lessonUnits: "23", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l24", title: "Remains and War Photographer", lessonUnits: "24", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l25", title: "Tissue and The Emigree", lessonUnits: "25", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l26-27", title: "Comparative Analysis of Poems", lessonUnits: "26-27", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l28", title: "Contextual and Thematic Links", lessonUnits: "28", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l29-30", title: "Introduction to Unseen Poetry", lessonUnits: "29-30", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l31", title: "Techniques for Unseen Poetry", lessonUnits: "31", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l32", title: "Comparative Analysis of Unseen Poems", lessonUnits: "32", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l33", title: "Understanding Non-Fiction Forms", lessonUnits: "33", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l34", title: "Writing Speeches and Letters", lessonUnits: "34", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l35", title: "Writing Articles and Opinion Pieces", lessonUnits: "35", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        { id: "english.y10.l36", title: "Planning, Drafting and Final Assessment", lessonUnits: "36", blockTitle: "Power and Conflict Poetry", year: 10, block: "poetry" },
        ],
      },
      {
        block: "paper1-revision",
        blockTitle: "Paper 1, An Inspector Calls and Poetry Revision",
        lessons: [
        { id: "english.y10.l37-39", title: "Literature Revision Consolidation", lessonUnits: "37-39", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        { id: "english.y10.l40-42", title: "Reviewing Power and Conflict Poems", lessonUnits: "40-42", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        { id: "english.y10.l43-44", title: "Reviewing Unseen Poetry", lessonUnits: "43-44", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        { id: "english.y10.l45-46", title: "Exam Practice and Timed Essays", lessonUnits: "45-46", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        { id: "english.y10.l47-48", title: "Paper 1 Section A - Understanding Questions", lessonUnits: "47-48", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        { id: "english.y10.l49-50", title: "Reading Comprehension Strategies", lessonUnits: "49-50", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        { id: "english.y10.l51-52", title: "Analysing Language and Structure", lessonUnits: "51-52", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        { id: "english.y10.l53-54", title: "Past Paper Practice and Peer Review", lessonUnits: "53-54", blockTitle: "Paper 1, An Inspector Calls and Poetry Revision", year: 10, block: "paper1-revision" },
        ],
      },
      {
        block: "macbeth-paper2",
        blockTitle: "Macbeth and Paper 2 Language Skills",
        lessons: [
        { id: "english.y10.l55-56", title: "Macbeth - Introduction and Context", lessonUnits: "55-56", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l57-58", title: "Macbeth Act 1 Analysis", lessonUnits: "57-58", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l59-60", title: "Macbeth Act 2 Analysis", lessonUnits: "59-60", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l61-62", title: "Macbeth Act 2 - Key Themes", lessonUnits: "61-62", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l63-64", title: "Macbeth Act 3 - Conflict Development", lessonUnits: "63-64", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l65", title: "Macbeth Act 4 - Themes and Characters", lessonUnits: "65", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l66-67", title: "Paper 2 Section A - Reading Skills", lessonUnits: "66-67", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l68-69", title: "Paper 2 - Question Types and Strategies", lessonUnits: "68-69", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l70", title: "Reading Comprehension Strategies", lessonUnits: "70", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l71", title: "Analysing Language and Structure", lessonUnits: "71", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        { id: "english.y10.l72", title: "Past Paper Practice", lessonUnits: "72", blockTitle: "Macbeth and Paper 2 Language Skills", year: 10, block: "macbeth-paper2" },
        ],
      },
      {
        block: "year-review",
        blockTitle: "Literature and Language Review",
        lessons: [
        { id: "english.y10.l73-77", title: "Macbeth and Poetry Consolidation", lessonUnits: "73-77", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l78-80", title: "Comparative Analysis - Power and Conflict", lessonUnits: "78-80", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l81-83", title: "Paper 1 and Paper 2 Writing Skills", lessonUnits: "81-83", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l84-86", title: "Creative and Viewpoint Writing", lessonUnits: "84-86", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l87-90", title: "Exam Technique and Revision", lessonUnits: "87-90", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l91-94", title: "Literature Revision - Key Texts", lessonUnits: "91-94", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l95-98", title: "Language Skills Revision", lessonUnits: "95-98", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l99-102", title: "Comparative Literature Practice", lessonUnits: "99-102", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l103-106", title: "Timed Exam Practice", lessonUnits: "103-106", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        { id: "english.y10.l107-108", title: "End of Year Review and Consolidation", lessonUnits: "107-108", blockTitle: "Literature and Language Review", year: 10, block: "year-review" },
        ],
      }
      ],
      year11: [
      {
        block: "christmas-carol",
        blockTitle: "A Christmas Carol and Language: Paper 2 Skills",
        lessons: [
        { id: "english.y11.l01-02", title: "A Christmas Carol - Introduction", lessonUnits: "1-2", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l03-06", title: "Character Analysis", lessonUnits: "3-6", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l07-10", title: "Themes and Motifs", lessonUnits: "7-10", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l11-13", title: "Writer's Methods", lessonUnits: "11-13", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l14-15", title: "Essay Writing Practice", lessonUnits: "14-15", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l16", title: "Contextual Understanding", lessonUnits: "16", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l17-18", title: "Paper 2 Reading Comprehension", lessonUnits: "17-18", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l19-20", title: "Language Analysis Skills", lessonUnits: "19-20", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        { id: "english.y11.l21-24", title: "Comparison and Viewpoint Writing", lessonUnits: "21-24", blockTitle: "A Christmas Carol and Language: Paper 2 Skills", year: 11, block: "christmas-carol" },
        ],
      },
      {
        block: "poetry-y11",
        blockTitle: "Power and Conflict and Unseen Poetry",
        lessons: [
        { id: "english.y11.l25-28", title: "Anthology Poems 1-5 Analysis", lessonUnits: "25-28", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
        { id: "english.y11.l29-30", title: "Unseen Poetry Analysis", lessonUnits: "29-30", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
        { id: "english.y11.l31-32", title: "Poems 6-10 and Comparison", lessonUnits: "31-32", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
        { id: "english.y11.l33-34", title: "Unseen Poetry Practice", lessonUnits: "33-34", blockTitle: "Power and Conflict and Unseen Poetry", year: 11, block: "poetry-y11" },
        ],
      },
      {
        block: "creative-reading",
        blockTitle: "Explorations in Creative Reading and Writing",
        lessons: [
        { id: "english.y11.l35", title: "Comparative Essay Writing", lessonUnits: "35", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
        { id: "english.y11.l36-38", title: "Reading Fiction Techniques", lessonUnits: "36-38", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
        { id: "english.y11.l39-43", title: "Narrative Structure Analysis", lessonUnits: "39-43", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
        { id: "english.y11.l44-46", title: "Descriptive Writing Techniques", lessonUnits: "44-46", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
        { id: "english.y11.l47-48", title: "Creative Writing Practice", lessonUnits: "47-48", blockTitle: "Explorations in Creative Reading and Writing", year: 11, block: "creative-reading" },
        ],
      },
      {
        block: "exam-focus",
        blockTitle: "Literature and Language Exam Focus",
        lessons: [
        { id: "english.y11.l49-52", title: "Paper 1 Revision - Key Texts", lessonUnits: "49-52", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        { id: "english.y11.l53-54", title: "Practice Papers - Paper 1", lessonUnits: "53-54", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        { id: "english.y11.l55-60", title: "Targeted Revision", lessonUnits: "55-60", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        { id: "english.y11.l61-62", title: "Paper 2 Revision - Key Texts", lessonUnits: "61-62", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        { id: "english.y11.l63-64", title: "Practice Papers - Paper 2", lessonUnits: "63-64", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        { id: "english.y11.l65", title: "Individual Targeted Revision", lessonUnits: "65", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        { id: "english.y11.l66-69", title: "GCSE Exam Preparation", lessonUnits: "66-69", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        { id: "english.y11.l69-72", title: "Final Practice Papers", lessonUnits: "69-72", blockTitle: "Literature and Language Exam Focus", year: 11, block: "exam-focus" },
        ],
      }
      ],
    },
  }
,
  maths: {
    label: "Mathematics",
    examBoard: "Edexcel",
    lessonsPerWeek: 2,
    lessons: [
      { id: "maths.y10.l01", title: "Place Value and Inequality Symbols", lessonUnits: "1", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l02", title: "Ordering Integers", lessonUnits: "2", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l03", title: "Decimals and Place Value", lessonUnits: "3", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l04-05", title: "Decimals and Fractions Connection", lessonUnits: "4-5", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l06", title: "Indices and Standard Form", lessonUnits: "6", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l07", title: "Integer Squares and Roots", lessonUnits: "7", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l08", title: "Powers of Small Integers", lessonUnits: "8", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l09", title: "Index Notation for Powers of 10", lessonUnits: "9", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l10", title: "Powers of 10 and Standard Form", lessonUnits: "10", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l11-12", title: "Factors, Multiples, and Primes", lessonUnits: "11-12", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l13", title: "Substituting into Formulae", lessonUnits: "13", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l14", title: "Simplifying and Manipulating Expressions", lessonUnits: "14", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l15", title: "Fractions", lessonUnits: "15", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l16", title: "Simplifying Ratios", lessonUnits: "16", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l17", title: "Dividing Quantities in a Given Ratio", lessonUnits: "17", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l18-19", title: "Solving Ratio Problems", lessonUnits: "18-19", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l20-22", title: "Direct and Inverse Proportion", lessonUnits: "20-22", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l23-25", title: "Graphs to Represent Proportion", lessonUnits: "23-25", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l26-27", title: "Multiplicative Reasoning", lessonUnits: "26-27", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l28-29", title: "Proportional Problems", lessonUnits: "28-29", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l30", title: "Multiplicative Reasoning Applications", lessonUnits: "30", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l31-33", title: "Word Problems with Multiplicative Reasoning", lessonUnits: "31-33", blockTitle: "Number", year: 10, block: "number" },
      { id: "maths.y10.l34-35", title: "Writing and Identifying Algebraic Forms", lessonUnits: "34-35", blockTitle: "Algebra", year: 10, block: "algebra" },
      { id: "maths.y10.l36-38", title: "Simplifying Algebraic Expressions", lessonUnits: "36-38", blockTitle: "Algebra", year: 10, block: "algebra" },
      { id: "maths.y10.l39-41", title: "Problem Solving with Algebra", lessonUnits: "39-41", blockTitle: "Algebra", year: 10, block: "algebra" },
      { id: "maths.y10.l42-44", title: "Expanding and Factorising", lessonUnits: "42-44", blockTitle: "Algebra", year: 10, block: "algebra" },
      { id: "maths.y10.l45-47", title: "Substituting and Using Formulae", lessonUnits: "45-47", blockTitle: "Algebra", year: 10, block: "algebra" },
      { id: "maths.y10.l48-50", title: "Geometric Constructions", lessonUnits: "48-50", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l51-52", title: "Constructions and Loci", lessonUnits: "51-52", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l53", title: "Perpendicular Distance", lessonUnits: "53", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l54", title: "Standard Units of Measure", lessonUnits: "54", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l55-56", title: "Measuring Line Segments and Angles", lessonUnits: "55-56", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l57-59", title: "Data Interpretation and Representation", lessonUnits: "57-59", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l60", title: "Scatter Graphs and Correlation", lessonUnits: "60", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l61-63", title: "Properties of Shapes", lessonUnits: "61-63", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l64-66", title: "Parallel Lines and Angle Facts", lessonUnits: "64-66", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l67-69", title: "Perimeter, Area, and Volume", lessonUnits: "67-69", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l70-72", title: "Circles, Cylinders, and Spheres", lessonUnits: "70-72", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l73-75", title: "Plans and Elevations", lessonUnits: "73-75", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
      { id: "maths.y10.l76-78", title: "Form and Solve Linear Equations", lessonUnits: "76-78", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
      { id: "maths.y10.l79-81", title: "Simultaneous Equations", lessonUnits: "79-81", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
      { id: "maths.y10.l82-84", title: "Sequences", lessonUnits: "82-84", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
      { id: "maths.y10.l85-87", title: "Inequalities", lessonUnits: "85-87", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
      { id: "maths.y10.l88-90", title: "Pythagoras' Theorem", lessonUnits: "88-90", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 10, block: "pythagoras" },
      { id: "maths.y10.l91-93", title: "Trigonometry in Right-Angled Triangles", lessonUnits: "91-93", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 10, block: "pythagoras" },
      { id: "maths.y10.l94-96", title: "Trigonometry Applications", lessonUnits: "94-96", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 10, block: "pythagoras" },
      { id: "maths.y10.l97-99", title: "Data and Sampling", lessonUnits: "97-99", blockTitle: "Statistics", year: 10, block: "statistics" },
      { id: "maths.y10.l100-102", title: "Measures of Central Tendency", lessonUnits: "100-102", blockTitle: "Statistics", year: 10, block: "statistics" },
      { id: "maths.y10.l103-105", title: "Analysing and Interpreting Data", lessonUnits: "103-105", blockTitle: "Statistics", year: 10, block: "statistics" },
      { id: "maths.y11.l01", title: "Translations", lessonUnits: "1", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l02", title: "Reflections", lessonUnits: "2", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l03-04", title: "Rotations", lessonUnits: "3-4", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l05", title: "Enlargement", lessonUnits: "5", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l06-07", title: "Combined Transformations", lessonUnits: "6-7", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l08-09", title: "Constructions, Loci, and Bearings", lessonUnits: "8-9", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l10-12", title: "Similarity and Congruence", lessonUnits: "10-12", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l13-15", title: "Vectors", lessonUnits: "13-15", blockTitle: "Geometry", year: 11, block: "geometry" },
      { id: "maths.y11.l16-18", title: "Probability Language and Scale", lessonUnits: "16-18", blockTitle: "Statistics and Probability", year: 11, block: "statistics-probability" },
      { id: "maths.y11.l19-21", title: "Combined Events and Tree Diagrams", lessonUnits: "19-21", blockTitle: "Statistics and Probability", year: 11, block: "statistics-probability" },
      { id: "maths.y11.l22-24", title: "Statistical Diagrams and Analysis", lessonUnits: "22-24", blockTitle: "Statistics and Probability", year: 11, block: "statistics-probability" },
      { id: "maths.y11.l25-27", title: "Plans, Elevations, and 3D Shapes", lessonUnits: "25-27", blockTitle: "Graphs", year: 11, block: "graphs" },
      { id: "maths.y11.l28-30", title: "Graphs of Linear and Quadratic Functions", lessonUnits: "28-30", blockTitle: "Graphs", year: 11, block: "graphs" },
      { id: "maths.y11.l31-33", title: "Rearranging Formulae", lessonUnits: "31-33", blockTitle: "Algebra", year: 11, block: "algebra-y11" },
      { id: "maths.y11.l34-35", title: "Graphs of Cubic and Reciprocal Functions", lessonUnits: "34-35", blockTitle: "Algebra", year: 11, block: "algebra-y11" },
      { id: "maths.y11.l36", title: "Simultaneous Equations (Advanced)", lessonUnits: "36", blockTitle: "Algebra", year: 11, block: "algebra-y11" },
      { id: "maths.y11.l37-39", title: "Quadratic Equations", lessonUnits: "37-39", blockTitle: "Equations and Inequalities", year: 11, block: "equations-y11" },
      { id: "maths.y11.l40-42", title: "Quadratic Inequalities", lessonUnits: "40-42", blockTitle: "Equations and Inequalities", year: 11, block: "equations-y11" },
      { id: "maths.y11.l43-45", title: "Algebraic Fractions", lessonUnits: "43-45", blockTitle: "Equations and Inequalities", year: 11, block: "equations-y11" },
      { id: "maths.y11.l46-48", title: "Trigonometry in Non-Right-Angled Triangles", lessonUnits: "46-48", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 11, block: "pythagoras-y11" },
      { id: "maths.y11.l49-51", title: "3D Trigonometry and Pythagoras", lessonUnits: "49-51", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 11, block: "pythagoras-y11" },
      { id: "maths.y11.l52-54", title: "Number and Algebra Revision", lessonUnits: "52-54", blockTitle: "Revision", year: 11, block: "revision" },
      { id: "maths.y11.l55-57", title: "Geometry and Measures Revision", lessonUnits: "55-57", blockTitle: "Revision", year: 11, block: "revision" },
      { id: "maths.y11.l58-60", title: "Statistics, Probability, and Graphs Revision", lessonUnits: "58-60", blockTitle: "Revision", year: 11, block: "revision" },
      { id: "maths.y11.l61-63", title: "Exam Technique and Practice Papers", lessonUnits: "61-63", blockTitle: "Revision", year: 11, block: "revision" },
      { id: "maths.y11.l64-66", title: "Final GCSE Exam Preparation", lessonUnits: "64-66", blockTitle: "Revision", year: 11, block: "revision" },
    ],
    byYear: {
      year10: [
      {
        block: "number",
        blockTitle: "Number",
        lessons: [
        { id: "maths.y10.l01", title: "Place Value and Inequality Symbols", lessonUnits: "1", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l02", title: "Ordering Integers", lessonUnits: "2", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l03", title: "Decimals and Place Value", lessonUnits: "3", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l04-05", title: "Decimals and Fractions Connection", lessonUnits: "4-5", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l06", title: "Indices and Standard Form", lessonUnits: "6", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l07", title: "Integer Squares and Roots", lessonUnits: "7", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l08", title: "Powers of Small Integers", lessonUnits: "8", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l09", title: "Index Notation for Powers of 10", lessonUnits: "9", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l10", title: "Powers of 10 and Standard Form", lessonUnits: "10", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l11-12", title: "Factors, Multiples, and Primes", lessonUnits: "11-12", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l13", title: "Substituting into Formulae", lessonUnits: "13", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l14", title: "Simplifying and Manipulating Expressions", lessonUnits: "14", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l15", title: "Fractions", lessonUnits: "15", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l16", title: "Simplifying Ratios", lessonUnits: "16", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l17", title: "Dividing Quantities in a Given Ratio", lessonUnits: "17", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l18-19", title: "Solving Ratio Problems", lessonUnits: "18-19", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l20-22", title: "Direct and Inverse Proportion", lessonUnits: "20-22", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l23-25", title: "Graphs to Represent Proportion", lessonUnits: "23-25", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l26-27", title: "Multiplicative Reasoning", lessonUnits: "26-27", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l28-29", title: "Proportional Problems", lessonUnits: "28-29", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l30", title: "Multiplicative Reasoning Applications", lessonUnits: "30", blockTitle: "Number", year: 10, block: "number" },
        { id: "maths.y10.l31-33", title: "Word Problems with Multiplicative Reasoning", lessonUnits: "31-33", blockTitle: "Number", year: 10, block: "number" },
        ],
      },
      {
        block: "algebra",
        blockTitle: "Algebra",
        lessons: [
        { id: "maths.y10.l34-35", title: "Writing and Identifying Algebraic Forms", lessonUnits: "34-35", blockTitle: "Algebra", year: 10, block: "algebra" },
        { id: "maths.y10.l36-38", title: "Simplifying Algebraic Expressions", lessonUnits: "36-38", blockTitle: "Algebra", year: 10, block: "algebra" },
        { id: "maths.y10.l39-41", title: "Problem Solving with Algebra", lessonUnits: "39-41", blockTitle: "Algebra", year: 10, block: "algebra" },
        { id: "maths.y10.l42-44", title: "Expanding and Factorising", lessonUnits: "42-44", blockTitle: "Algebra", year: 10, block: "algebra" },
        { id: "maths.y10.l45-47", title: "Substituting and Using Formulae", lessonUnits: "45-47", blockTitle: "Algebra", year: 10, block: "algebra" },
        ],
      },
      {
        block: "graphs-geometry",
        blockTitle: "Graphs, Geometry, Shapes and Functions",
        lessons: [
        { id: "maths.y10.l48-50", title: "Geometric Constructions", lessonUnits: "48-50", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l51-52", title: "Constructions and Loci", lessonUnits: "51-52", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l53", title: "Perpendicular Distance", lessonUnits: "53", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l54", title: "Standard Units of Measure", lessonUnits: "54", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l55-56", title: "Measuring Line Segments and Angles", lessonUnits: "55-56", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l57-59", title: "Data Interpretation and Representation", lessonUnits: "57-59", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l60", title: "Scatter Graphs and Correlation", lessonUnits: "60", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l61-63", title: "Properties of Shapes", lessonUnits: "61-63", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l64-66", title: "Parallel Lines and Angle Facts", lessonUnits: "64-66", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l67-69", title: "Perimeter, Area, and Volume", lessonUnits: "67-69", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l70-72", title: "Circles, Cylinders, and Spheres", lessonUnits: "70-72", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        { id: "maths.y10.l73-75", title: "Plans and Elevations", lessonUnits: "73-75", blockTitle: "Graphs, Geometry, Shapes and Functions", year: 10, block: "graphs-geometry" },
        ],
      },
      {
        block: "equations",
        blockTitle: "Equations and Inequalities",
        lessons: [
        { id: "maths.y10.l76-78", title: "Form and Solve Linear Equations", lessonUnits: "76-78", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
        { id: "maths.y10.l79-81", title: "Simultaneous Equations", lessonUnits: "79-81", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
        { id: "maths.y10.l82-84", title: "Sequences", lessonUnits: "82-84", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
        { id: "maths.y10.l85-87", title: "Inequalities", lessonUnits: "85-87", blockTitle: "Equations and Inequalities", year: 10, block: "equations" },
        ],
      },
      {
        block: "pythagoras",
        blockTitle: "Pythagoras' Theorem and Trigonometry",
        lessons: [
        { id: "maths.y10.l88-90", title: "Pythagoras' Theorem", lessonUnits: "88-90", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 10, block: "pythagoras" },
        { id: "maths.y10.l91-93", title: "Trigonometry in Right-Angled Triangles", lessonUnits: "91-93", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 10, block: "pythagoras" },
        { id: "maths.y10.l94-96", title: "Trigonometry Applications", lessonUnits: "94-96", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 10, block: "pythagoras" },
        ],
      },
      {
        block: "statistics",
        blockTitle: "Statistics",
        lessons: [
        { id: "maths.y10.l97-99", title: "Data and Sampling", lessonUnits: "97-99", blockTitle: "Statistics", year: 10, block: "statistics" },
        { id: "maths.y10.l100-102", title: "Measures of Central Tendency", lessonUnits: "100-102", blockTitle: "Statistics", year: 10, block: "statistics" },
        { id: "maths.y10.l103-105", title: "Analysing and Interpreting Data", lessonUnits: "103-105", blockTitle: "Statistics", year: 10, block: "statistics" },
        ],
      }
      ],
      year11: [
      {
        block: "geometry",
        blockTitle: "Geometry",
        lessons: [
        { id: "maths.y11.l01", title: "Translations", lessonUnits: "1", blockTitle: "Geometry", year: 11, block: "geometry" },
        { id: "maths.y11.l02", title: "Reflections", lessonUnits: "2", blockTitle: "Geometry", year: 11, block: "geometry" },
        { id: "maths.y11.l03-04", title: "Rotations", lessonUnits: "3-4", blockTitle: "Geometry", year: 11, block: "geometry" },
        { id: "maths.y11.l05", title: "Enlargement", lessonUnits: "5", blockTitle: "Geometry", year: 11, block: "geometry" },
        { id: "maths.y11.l06-07", title: "Combined Transformations", lessonUnits: "6-7", blockTitle: "Geometry", year: 11, block: "geometry" },
        { id: "maths.y11.l08-09", title: "Constructions, Loci, and Bearings", lessonUnits: "8-9", blockTitle: "Geometry", year: 11, block: "geometry" },
        { id: "maths.y11.l10-12", title: "Similarity and Congruence", lessonUnits: "10-12", blockTitle: "Geometry", year: 11, block: "geometry" },
        { id: "maths.y11.l13-15", title: "Vectors", lessonUnits: "13-15", blockTitle: "Geometry", year: 11, block: "geometry" },
        ],
      },
      {
        block: "statistics-probability",
        blockTitle: "Statistics and Probability",
        lessons: [
        { id: "maths.y11.l16-18", title: "Probability Language and Scale", lessonUnits: "16-18", blockTitle: "Statistics and Probability", year: 11, block: "statistics-probability" },
        { id: "maths.y11.l19-21", title: "Combined Events and Tree Diagrams", lessonUnits: "19-21", blockTitle: "Statistics and Probability", year: 11, block: "statistics-probability" },
        { id: "maths.y11.l22-24", title: "Statistical Diagrams and Analysis", lessonUnits: "22-24", blockTitle: "Statistics and Probability", year: 11, block: "statistics-probability" },
        ],
      },
      {
        block: "graphs",
        blockTitle: "Graphs",
        lessons: [
        { id: "maths.y11.l25-27", title: "Plans, Elevations, and 3D Shapes", lessonUnits: "25-27", blockTitle: "Graphs", year: 11, block: "graphs" },
        { id: "maths.y11.l28-30", title: "Graphs of Linear and Quadratic Functions", lessonUnits: "28-30", blockTitle: "Graphs", year: 11, block: "graphs" },
        ],
      },
      {
        block: "algebra-y11",
        blockTitle: "Algebra",
        lessons: [
        { id: "maths.y11.l31-33", title: "Rearranging Formulae", lessonUnits: "31-33", blockTitle: "Algebra", year: 11, block: "algebra-y11" },
        { id: "maths.y11.l34-35", title: "Graphs of Cubic and Reciprocal Functions", lessonUnits: "34-35", blockTitle: "Algebra", year: 11, block: "algebra-y11" },
        { id: "maths.y11.l36", title: "Simultaneous Equations (Advanced)", lessonUnits: "36", blockTitle: "Algebra", year: 11, block: "algebra-y11" },
        ],
      },
      {
        block: "equations-y11",
        blockTitle: "Equations and Inequalities",
        lessons: [
        { id: "maths.y11.l37-39", title: "Quadratic Equations", lessonUnits: "37-39", blockTitle: "Equations and Inequalities", year: 11, block: "equations-y11" },
        { id: "maths.y11.l40-42", title: "Quadratic Inequalities", lessonUnits: "40-42", blockTitle: "Equations and Inequalities", year: 11, block: "equations-y11" },
        { id: "maths.y11.l43-45", title: "Algebraic Fractions", lessonUnits: "43-45", blockTitle: "Equations and Inequalities", year: 11, block: "equations-y11" },
        ],
      },
      {
        block: "pythagoras-y11",
        blockTitle: "Pythagoras' Theorem and Trigonometry",
        lessons: [
        { id: "maths.y11.l46-48", title: "Trigonometry in Non-Right-Angled Triangles", lessonUnits: "46-48", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 11, block: "pythagoras-y11" },
        { id: "maths.y11.l49-51", title: "3D Trigonometry and Pythagoras", lessonUnits: "49-51", blockTitle: "Pythagoras' Theorem and Trigonometry", year: 11, block: "pythagoras-y11" },
        ],
      },
      {
        block: "revision",
        blockTitle: "Revision",
        lessons: [
        { id: "maths.y11.l52-54", title: "Number and Algebra Revision", lessonUnits: "52-54", blockTitle: "Revision", year: 11, block: "revision" },
        { id: "maths.y11.l55-57", title: "Geometry and Measures Revision", lessonUnits: "55-57", blockTitle: "Revision", year: 11, block: "revision" },
        { id: "maths.y11.l58-60", title: "Statistics, Probability, and Graphs Revision", lessonUnits: "58-60", blockTitle: "Revision", year: 11, block: "revision" },
        { id: "maths.y11.l61-63", title: "Exam Technique and Practice Papers", lessonUnits: "61-63", blockTitle: "Revision", year: 11, block: "revision" },
        { id: "maths.y11.l64-66", title: "Final GCSE Exam Preparation", lessonUnits: "64-66", blockTitle: "Revision", year: 11, block: "revision" },
        ],
      }
      ],
    },
  }
};

export const LEARNING_JOURNEY = {
  english: {
    year10: [
      "An Inspector Calls and Paper 1 Language Skills",
      "Power and Conflict Poetry",
      "Paper 1, An Inspector Calls and Poetry Revision",
      "Macbeth and Paper 2 Language Skills",
      "Literature and Language Review",
    ],
    year11: [
      "A Christmas Carol and Language: Paper 2 Skills",
      "Power and Conflict and Unseen Poetry",
      "Explorations in Creative Reading and Writing",
      "Literature and Language Exam Focus",
    ],
  },
  maths: {
    year10: [
      "Number",
      "Algebra",
      "Graphs, Geometry, Shapes and Functions",
      "Equations and Inequalities",
      "Pythagoras' Theorem and Trigonometry",
      "Statistics",
    ],
    year11: [
      "Geometry",
      "Statistics and Probability",
      "Graphs",
      "Algebra",
      "Equations and Inequalities",
      "Pythagoras' Theorem and Trigonometry",
      "Revision",
    ],
  },
};

export function getLessonsForYear(
  subject: "english" | "maths",
  year: 10 | 11,
): LessonMeta[] {
  return CURRICULUM[subject].lessons.filter((l) => l.year === year);
}

/** @deprecated Use CURRICULUM instead */
export const PILOT_LESSONS = CURRICULUM;