/** Curated lesson units from Purple Ruler SoW PDFs (grouped as in scheme). */

function L(units, block, blockTitle, title, unitAim, objectives) {
  return { lessonUnits: units, block, blockTitle, title, unitAim, objectives };
}

export const ENGLISH_Y10 = [
  L("1-3", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "An Inspector Calls - Context", "Understand and analyse the social, historical, and cultural context of An Inspector Calls.", ["Understand social, historical, and cultural context", "Explain Priestley's intentions and 1912 vs 1945", "Compare attitudes across time periods"]),
  L("4-5", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "An Inspector Calls - Act 1", "Analyse key events and characters introduced in Act 1.", ["Analyse Act 1 events and character introductions", "Discuss class divisions and social responsibility", "Compare 1912 and 1945 societal norms"]),
  L("6-7", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "An Inspector Calls - Act 2", "Explore development of themes and characters in Act 2.", ["Track theme development in Act 2", "Analyse character relationships", "Examine responsibility and guilt"]),
  L("8-9", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "An Inspector Calls - Act 2 Conflict", "Analyse escalating conflict and character dynamics in Act 2.", ["Analyse changing relationships", "Discuss evolving themes", "Examine intensifying conflicts"]),
  L("10-11", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "An Inspector Calls - Act 3", "Understand resolution of the plot and thematic implications.", ["Analyse final revelations", "Discuss social critique", "Explore personal accountability"]),
  L("12", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "Character Studies", "Examine development and motivations of key characters.", ["Trace character evolution", "Analyse motivations", "Evaluate impact of revelations"]),
  L("13-14", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "Themes and Motifs", "Identify and analyse main themes and recurring motifs.", ["Identify central themes", "Analyse motifs", "Link themes to context"]),
  L("15", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "Context and Exam Questions", "Apply contextual knowledge to exam-style questions.", ["Use context in answers", "Support interpretations with evidence", "Integrate themes into responses"]),
  L("16-17", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "Descriptive Writing Techniques", "Learn and practise descriptive writing techniques for Paper 1 Q5.", ["Understand descriptive techniques", "Write from visual stimuli", "Use sensory detail effectively"]),
  L("18", "inspector-paper1", "An Inspector Calls and Paper 1 Language Skills", "Descriptive Writing Draft", "Plan, draft, and improve a descriptive piece.", ["Plan coherent descriptions", "Draft with detail", "Improve through peer review"]),
  L("19", "power-conflict", "Power and Conflict Poetry", "Anthology Introduction", "Gain an overview of the Power and Conflict anthology and its poets.", ["Know anthology poets and poems", "Understand cluster themes", "Use poetry terminology accurately"]),
  L("20", "power-conflict", "Power and Conflict Poetry", "Ozymandias and London", "Close reading of Ozymandias and London.", ["Analyse power and legacy", "Explore oppression and suffering", "Link context to meaning"]),
  L("21", "power-conflict", "Power and Conflict Poetry", "My Last Duchess and Charge", "Close reading of My Last Duchess and The Charge of the Light Brigade.", ["Analyse dramatic monologue", "Explore heroism and duty", "Use contextual knowledge"]),
  L("22", "power-conflict", "Power and Conflict Poetry", "Bayonet Charge and Poppies", "Close reading of Bayonet Charge and Poppies.", ["Analyse fear and chaos in war", "Explore loss and memory", "Compare perspectives on conflict"]),
  L("23", "power-conflict", "Power and Conflict Poetry", "Anthology Poem Study", "Analyse imagery, tone, and content of anthology poems.", ["Annotate poems in detail", "Explain effects of language", "Identify structural choices"]),
  L("24", "power-conflict", "Power and Conflict Poetry", "Anthology Poem Study II", "Continue detailed analysis of anthology poems.", ["Compare methods within poems", "Evaluate writers' intentions", "Use quotations precisely"]),
  L("25", "power-conflict", "Power and Conflict Poetry", "Anthology Poem Study III", "Develop confident analytical responses to studied poems.", ["Build analytical paragraphs", "Link technique to theme", "Maintain formal tone"]),
  L("26-27", "power-conflict", "Power and Conflict Poetry", "Comparative Poetry Analysis", "Develop comparative analysis skills across poems.", ["Compare themes and methods", "Structure comparative responses", "Use connectives effectively"]),
  L("28", "power-conflict", "Power and Conflict Poetry", "Context and Thematic Links", "Understand historical and cultural context of anthology poems.", ["Research contextual background", "Identify thematic links", "Present findings clearly"]),
  L("29-30", "power-conflict", "Power and Conflict Poetry", "Contextual Thematic Study", "Connect context to thematic interpretation across poems.", ["Explain how context shapes meaning", "Compare poets' viewpoints", "Evaluate effectiveness of methods"]),
  L("31", "unseen-paper2", "Unseen Poetry and Paper 2 Writing", "Introduction to Unseen Poetry", "Learn strategies for analysing unseen poems.", ["Use a step-by-step approach", "Annotate for devices and themes", "Identify form and structure"]),
  L("32", "unseen-paper2", "Unseen Poetry and Paper 2 Writing", "Approaching Unseen Poems", "Practise techniques for approaching and interpreting unseen poetry.", ["Identify tone and imagery", "Explain effects on the reader", "Compare with studied poems"]),
  L("33", "unseen-paper2", "Unseen Poetry and Paper 2 Writing", "Comparing Unseen Poems", "Develop skills comparing two unseen poems.", ["Compare themes and methods", "Structure a comparative response", "Use evidence from both poems"]),
  L("34", "unseen-paper2", "Unseen Poetry and Paper 2 Writing", "Non-Fiction Forms", "Understand different forms and purposes of non-fiction writing.", ["Identify forms such as articles and speeches", "Analyse purpose and audience", "Recognise persuasive techniques"]),
  L("35", "unseen-paper2", "Unseen Poetry and Paper 2 Writing", "Speeches and Letters", "Practise writing speeches and letters to present a viewpoint.", ["Craft persuasive openings", "Use rhetorical devices", "Maintain appropriate register"]),
  L("36", "unseen-paper2", "Unseen Poetry and Paper 2 Writing", "Articles and Opinion Pieces", "Develop skills writing articles and opinion pieces.", ["Structure arguments clearly", "Use evidence and examples", "Engage the reader"]),
  L("37-39", "revision-paper1", "Paper 1 Revision and Consolidation", "Literature Revision Consolidation", "Consolidate understanding of literature texts and exam technique.", ["Revise key scenes and themes", "Practise analytical writing", "Improve exam technique"]),
  L("40-42", "revision-paper1", "Paper 1 Revision and Consolidation", "Reviewing An Inspector Calls", "Revise key elements of An Inspector Calls.", ["Revise characters and themes", "Practise extract responses", "Use quotations effectively"]),
  L("43-44", "revision-paper1", "Paper 1 Revision and Consolidation", "Reviewing Anthology Poems", "Revise selected Power and Conflict poems.", ["Consolidate poem knowledge", "Practise comparative analysis", "Refine analytical vocabulary"]),
  L("45-46", "revision-paper1", "Paper 1 Revision and Consolidation", "Reviewing Unseen Poetry", "Refresh techniques for unseen poetry.", ["Practise unseen approaches", "Analyse structure and language", "Write timed responses"]),
  L("47-48", "revision-paper1", "Paper 1 Revision and Consolidation", "Exam Practice Timed Essays", "Practise answering exam-style questions under timed conditions.", ["Manage time in exams", "Plan essays quickly", "Review strengths and gaps"]),
  L("49-50", "revision-paper1", "Paper 1 Revision and Consolidation", "Further Exam Practice", "Continue timed practice and refinement of exam responses.", ["Apply feedback to writing", "Refine analytical arguments", "Build exam confidence"]),
  L("51-52", "language-paper1", "Paper 1 Reading Skills", "Paper 1 Section A Question Types", "Learn different Paper 1 reading question types and strategies.", ["Recognise question types", "Select relevant evidence", "Structure clear answers"]),
  L("53-54", "language-paper1", "Paper 1 Reading Skills", "Language and Structure Analysis", "Practise analysing language and structure in unseen texts.", ["Identify methods and effects", "Use subject terminology", "Practise with past paper questions"]),
  L("55-56", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Macbeth - Context Introduction", "Understand historical and cultural context of Macbeth.", ["Explore Jacobean context", "Identify key themes", "Introduce main characters"]),
  L("57-58", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Macbeth - Act 1", "Analyse key events and characters in Act 1.", ["Analyse Act 1 events", "Explore ambition and prophecy", "Use evidence from the play"]),
  L("59-60", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Macbeth - Act 2", "Explore development of themes and characters in Act 2.", ["Analyse guilt and ambition", "Track character changes", "Discuss dramatic methods"]),
  L("61-62", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Macbeth - Act 3", "Understand escalating conflict in Act 3.", ["Analyse conflict development", "Explore thematic significance", "Compare across acts"]),
  L("63-64", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Macbeth - Act 4", "Analyse themes and character development in Act 4.", ["Explore supernatural elements", "Analyse character evolution", "Compare with earlier acts"]),
  L("65", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Macbeth - Act 5", "Understand resolution and overall themes in Act 5.", ["Analyse the play's conclusion", "Discuss moral implications", "Evaluate Shakespeare's message"]),
  L("66-67", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Paper 2 Section A Reading", "Develop Paper 2 reading comprehension and question techniques.", ["Understand question types", "Use evidence effectively", "Compare writers' methods"]),
  L("68-69", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Reading Comprehension Strategies", "Improve reading comprehension strategies for Paper 2.", ["Use active reading strategies", "Summarise key ideas", "Expand vocabulary in context"]),
  L("70", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Analysing Language and Structure", "Practise analysing language and structure in non-fiction texts.", ["Identify language features", "Explain structural effects", "Compare texts"]),
  L("71", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Past Paper Reading Practice", "Use past paper questions to practise reading skills.", ["Apply strategies under timed conditions", "Interpret questions accurately", "Review answers with criteria"]),
  L("72", "macbeth-paper2", "Macbeth and Paper 2 Language Skills", "Peer Review Reading Responses", "Improve comprehension through peer review and feedback.", ["Give constructive feedback", "Revise responses", "Reflect on progress"]),
  L("73-77", "lit-review", "Literature and Language Review", "Macbeth and Poetry Consolidation", "Consolidate understanding of Macbeth and anthology poetry.", ["Revise key scenes and poems", "Practise comparative analysis", "Strengthen quotation use"]),
  L("78-80", "lit-review", "Literature and Language Review", "Comparative Poetry and Themes", "Practise comparing Power and Conflict poems.", ["Identify thematic links", "Compare methods", "Write comparative essays"]),
  L("81-83", "lit-review", "Literature and Language Review", "Timed Essay Exam Practice", "Improve exam technique through timed essay practice.", ["Plan under time pressure", "Write cohesive arguments", "Use feedback to improve"]),
  L("84-86", "lit-review", "Literature and Language Review", "Paper 1 and 2 Writing Skills", "Develop descriptive and viewpoint writing for Papers 1 and 2.", ["Practise descriptive writing", "Craft viewpoint arguments", "Edit for accuracy and style"]),
  L("87-90", "lit-review", "Literature and Language Review", "Year 10 General Recap", "Recap key topics and skills from Year 10.", ["Review core concepts", "Practise exam-style questions", "Set goals for Year 11"]),
  L("91-100", "lit-review", "Literature and Language Review", "Literature Reinforcement", "Reinforce literature knowledge and analytical skills.", ["Deepen text understanding", "Practise extended responses", "Address individual gaps"]),
  L("101-104", "lit-review", "Literature and Language Review", "Language Skills Reinforcement", "Develop language skills for GCSE papers.", ["Strengthen reading analysis", "Improve writing accuracy", "Build exam confidence"]),
  L("105-108", "lit-review", "Literature and Language Review", "Comparative and Final Review", "Compare themes across texts and consolidate Year 10 learning.", ["Make cross-text connections", "Timed practice", "Reflect on progress"]),
];

export const ENGLISH_Y11 = [
  L("1-2", "christmas-carol", "A Christmas Carol and Paper 2 Skills", "A Christmas Carol - Introduction", "Understand plot, characters, and themes of A Christmas Carol.", ["Understand Victorian context", "Follow Scrooge's transformation", "Identify key characters"]),
  L("3-6", "christmas-carol", "A Christmas Carol and Paper 2 Skills", "Character Analysis", "Detailed study of key characters in A Christmas Carol.", ["Analyse Scrooge's arc", "Explore the Cratchit family", "Examine the three spirits"]),
  L("7-10", "christmas-carol", "A Christmas Carol and Paper 2 Skills", "Themes and Motifs", "Explore major themes and motifs in the novella.", ["Explore redemption", "Discuss social injustice", "Analyse time and memory"]),
  L("11-13", "christmas-carol", "A Christmas Carol and Paper 2 Skills", "Writer's Methods", "Analyse Dickens' writing techniques.", ["Analyse descriptive language", "Explore symbolism", "Evaluate narrative voice"]),
  L("14-15", "christmas-carol", "A Christmas Carol and Paper 2 Skills", "Essay Writing Practice", "Practise exam-style questions on A Christmas Carol.", ["Write character essays", "Explore theme questions", "Use contextual knowledge"]),
  L("16", "language-paper2", "A Christmas Carol and Paper 2 Skills", "Paper 2 Skills Overview", "Develop skills for Language Paper 2.", ["Understand Paper 2 demands", "Practise comprehension", "Build analytical vocabulary"]),
  L("17-18", "language-paper2", "A Christmas Carol and Paper 2 Skills", "Reading Comprehension", "Practise reading comprehension techniques for Paper 2.", ["Use active reading", "Summarise key ideas", "Answer exam-style questions"]),
  L("25-28", "poetry-y11", "Power and Conflict and Unseen Poetry", "Anthology Poems 1-5", "Detailed study of anthology poems from both clusters.", ["Annotate poems thoroughly", "Identify themes and methods", "Use comparative links"]),
  L("29-30", "poetry-y11", "Power and Conflict and Unseen Poetry", "Unseen Poetry Skills", "Develop skills analysing unseen poetry.", ["Use a clear analytical method", "Compare unseen poems", "Explain effects of language"]),
  L("31-32", "poetry-y11", "Power and Conflict and Unseen Poetry", "Poems 6-10 Analysis", "Thematic and structural analysis of further anthology poems.", ["Identify themes", "Analyse structure", "Evaluate effectiveness"]),
  L("33-34", "poetry-y11", "Power and Conflict and Unseen Poetry", "Contextual Comparison", "Understand context and compare poems.", ["Research contextual background", "Compare across poems", "Present findings"]),
  L("35", "poetry-y11", "Power and Conflict and Unseen Poetry", "Unseen Poetry Practice", "Practise approaching and analysing unseen poetry.", ["Apply unseen strategies", "Analyse form and imagery", "Write timed responses"]),
  L("36-38", "paper1-creative", "Paper 1 Explorations in Creative Reading and Writing", "Reading Fiction", "Develop techniques for reading and understanding fiction texts.", ["Analyse character and plot", "Identify themes", "Use evidence"]),
  L("39-43", "paper1-creative", "Paper 1 Explorations in Creative Reading and Writing", "Narrative Structure", "Understand and analyse narrative structures.", ["Analyse plot structure", "Explore viewpoint", "Discuss symbolism"]),
  L("44-46", "paper1-creative", "Paper 1 Explorations in Creative Reading and Writing", "Descriptive Writing", "Practise effective descriptive writing techniques.", ["Use sensory language", "Show rather than tell", "Structure descriptions"]),
  L("47-48", "paper1-creative", "Paper 1 Explorations in Creative Reading and Writing", "Creative Writing", "Craft engaging and coherent narratives.", ["Develop plot and character", "Use dialogue effectively", "Revise for impact"]),
  L("49-52", "exam-focus", "Literature and Language Exam Focus", "Key Texts Revision", "Review and consolidate knowledge of key literature texts.", ["Recap plot and themes", "Analyse quotations", "Plan exam essays"]),
  L("53-54", "exam-focus", "Literature and Language Exam Focus", "Practice Papers", "Timed practice of past exam papers.", ["Simulate exam conditions", "Manage time", "Review answers"]),
  L("55-60", "exam-focus", "Literature and Language Exam Focus", "Targeted Revision", "Address individual learner weaknesses.", ["Set personal targets", "Practise weak areas", "Use feedback"]),
  L("61-62", "exam-focus", "Literature and Language Exam Focus", "Paper 2 Revision", "Review and consolidate Paper 2 knowledge and skills.", ["Recap non-fiction skills", "Practise comparison", "Strengthen writing"]),
  L("63-64", "exam-focus", "Literature and Language Exam Focus", "Further Practice Papers", "Continue timed practice of past papers.", ["Apply exam strategies", "Improve timing", "Reflect on progress"]),
  L("65", "exam-focus", "Literature and Language Exam Focus", "Targeted Final Revision", "Focus revision on priority areas before exams.", ["Personalised study plan", "Practise priority skills", "Build confidence"]),
  L("66-69", "exam-focus", "Literature and Language Exam Focus", "GCSE Final Exam Preparation", "Targeted preparation for final GCSE exams.", ["Use exam techniques", "Practise under pressure", "Reduce exam anxiety"]),
  L("69-72", "exam-focus", "Literature and Language Exam Focus", "Final Practice Papers", "Complete final timed practice papers.", ["Full exam simulation", "Review collectively", "Refine strategies"]),
];

export const MATHS_Y10 = [
  L("1", "number", "Number", "Place Value and Inequality Symbols", "Understand place value and use inequality symbols to order numbers.", ["Use inequality symbols correctly", "Order integers, decimals, and fractions", "Apply place value in context"]),
  L("2", "number", "Number", "Ordering Integers", "Order positive and negative integers.", ["Order integers on a number line", "Apply ordering in real contexts", "Compare negative values"]),
  L("3", "number", "Number", "Decimals and Place Value", "Understand decimals, operations, and conversions.", ["Perform decimal operations", "Convert between forms", "Solve word problems with decimals"]),
  L("4-5", "number", "Number", "Decimals and Fractions", "Convert between decimals and fractions.", ["Convert terminating and recurring decimals", "Identify rational numbers", "Solve conversion problems"]),
  L("6", "number", "Number", "Indices and Standard Form", "Use index notation and standard form.", ["Write expressions using indices", "Convert to standard form", "Calculate with indices"]),
  L("7", "number", "Number", "Squares, Cubes and Roots", "Recall squares, cubes, and roots.", ["Use integer squares up to 10x10", "Find square roots", "Apply in calculations"]),
  L("8", "number", "Number", "Powers of Integers", "Identify and use powers in calculations.", ["Identify common powers", "Use powers in problems", "Avoid common misconceptions"]),
  L("9", "number", "Number", "Index Notation for Powers of 10", "Use index notation for powers of 10.", ["Express numbers in index form", "Convert standard form", "Apply negative indices"]),
  L("10", "number", "Number", "Factors, Multiples and Primes", "Identify factors, multiples, and primes; find HCF and LCM.", ["List factors and multiples", "Use prime factorisation", "Solve HCF and LCM problems"]),
  L("11-12", "number", "Number", "Algebraic Notation", "Write and manipulate basic algebraic notation.", ["Use conventional notation", "Substitute into expressions", "Expand single brackets"]),
  L("13", "number", "Number", "Substitution into Formulae", "Substitute values into formulae.", ["Substitute accurately", "Solve real-world problems", "Work with powers in formulae"]),
  L("14", "number", "Number", "Simplifying Expressions", "Simplify and manipulate expressions.", ["Collect like terms", "Expand brackets", "Factorise simple expressions"]),
  L("15", "number", "Number", "Fractions Operations", "Perform operations with fractions.", ["Add, subtract, multiply, divide fractions", "Convert between forms", "Solve fraction word problems"]),
  L("16", "number", "Number", "Comparing Fractions, Decimals, Percentages", "Compare and order fractions, decimals, and percentages.", ["Convert between forms", "Order mixed sets", "Choose appropriate methods"]),
  L("17", "number", "Number", "Ratio Basics", "Understand and simplify ratios.", ["Simplify ratios", "Use ratio notation", "Apply to real contexts"]),
  L("18-19", "number", "Number", "Ratio Problems", "Solve problems involving ratios.", ["Divide quantities in a ratio", "Solve ratio word problems", "Interpret answers"]),
  L("20-22", "number", "Number", "Proportion", "Understand direct and inverse proportion.", ["Recognise direct proportion", "Recognise inverse proportion", "Solve proportion problems"]),
  L("23-25", "number", "Number", "Graphs of Proportion", "Interpret and draw graphs of proportional relationships.", ["Plot proportional graphs", "Interpret gradient", "Link graphs to equations"]),
  L("26-27", "number", "Number", "Multiplicative Reasoning", "Apply multiplicative reasoning to solve problems.", ["Identify multiplicative relationships", "Scale quantities", "Solve scaling problems"]),
  L("28-29", "number", "Number", "Proportion Word Problems", "Solve direct and inverse proportion word problems.", ["Translate word problems", "Use y=kx and y=k/x", "Check solutions"]),
  L("30", "number", "Number", "Multiplicative Reasoning Applications", "Apply multiplicative reasoning in finance and growth contexts.", ["Solve real-world problems", "Use multiplicative strategies", "Interpret results"]),
  L("31-33", "number", "Number", "Ratio and Multiplicative Problems", "Solve complex ratio and multiplicative reasoning problems.", ["Break down word problems", "Choose correct methods", "Communicate reasoning"]),
  L("34-35", "algebra", "Algebra", "Algebraic Forms", "Identify and write algebraic expressions, equations, and formulae.", ["Translate words to algebra", "Distinguish expression types", "Form expressions from contexts"]),
  L("36-38", "algebra", "Algebra", "Simplifying Algebra", "Simplify expressions using index notation.", ["Collect like terms", "Use index laws", "Multiply algebraic terms"]),
  L("39-41", "algebra", "Algebra", "Expressions and Formulae Problems", "Formulate and solve problems with expressions and formulae.", ["Form equations from shapes", "Solve simple equations", "Apply to area and perimeter"]),
  L("42-44", "algebra", "Algebra", "Factorising and Equivalence", "Factorise expressions and recognise equivalence.", ["Factorise with single brackets", "Show equivalence", "Extract common factors"]),
  L("45-47", "algebra", "Algebra", "Substitution and Formulae", "Substitute into formulae and derive simple formulae.", ["Substitute into complex expressions", "Derive formulae from contexts", "Evaluate results"]),
  L("48-50", "geometry", "Graphs, Geometry, Shapes and Functions", "Perpendicular Bisector Construction", "Construct perpendicular bisectors and standard constructions.", ["Use ruler and compass", "Construct accurately", "Apply construction skills"]),
  L("51-52", "geometry", "Graphs, Geometry, Shapes and Functions", "Angle Bisector and Perpendiculars", "Construct angle bisectors and perpendiculars from a point.", ["Construct angle bisectors", "Draw perpendicular lines", "Solve construction problems"]),
  L("53", "geometry", "Graphs, Geometry, Shapes and Functions", "Loci", "Construct and interpret loci.", ["Draw loci for equidistant points", "Solve loci problems", "Interpret conditions"]),
  L("54", "geometry", "Graphs, Geometry, Shapes and Functions", "Bearings", "Use bearings in navigation problems.", ["Measure three-figure bearings", "Draw bearings accurately", "Solve navigation problems"]),
  L("55-56", "geometry", "Graphs, Geometry, Shapes and Functions", "Properties of Shapes", "Understand properties of 2D shapes.", ["Identify shape properties", "Calculate angles in shapes", "Solve shape problems"]),
  L("57-59", "geometry", "Graphs, Geometry, Shapes and Functions", "Angles in Parallel Lines", "Use angle facts with parallel lines.", ["Identify alternate and corresponding angles", "Find unknown angles", "Explain reasoning"]),
  L("60", "geometry", "Graphs, Geometry, Shapes and Functions", "Angle Problems", "Solve multi-step angle problems.", ["Combine angle facts", "Justify steps", "Check solutions"]),
  L("61-63", "geometry", "Graphs, Geometry, Shapes and Functions", "Perimeter and Area", "Calculate perimeter and area of 2D shapes.", ["Use area formulas", "Decompose compound shapes", "Solve context problems"]),
  L("64", "geometry", "Graphs, Geometry, Shapes and Functions", "Volume", "Calculate volume of 3D shapes.", ["Use volume formulas", "Solve cylinder problems", "Apply units correctly"]),
  L("65-66", "geometry", "Graphs, Geometry, Shapes and Functions", "Interior and Exterior Angles", "Calculate interior and exterior angles of polygons.", ["Use angle sum formulas", "Find angles in regular polygons", "Relate interior and exterior angles"]),
  L("67-69", "geometry", "Graphs, Geometry, Shapes and Functions", "Circle Properties", "Use circumference and area of circles.", ["Calculate circumference", "Calculate area", "Solve circle problems"]),
  L("70-71", "geometry", "Graphs, Geometry, Shapes and Functions", "Perimeter Area Volume Review", "Apply perimeter, area, and volume in problems.", ["Choose correct formulas", "Solve multi-step problems", "Check units"]),
  L("72", "geometry", "Graphs, Geometry, Shapes and Functions", "Composite Measures", "Solve problems combining perimeter, area, and volume.", ["Break problems into steps", "Combine measures", "Interpret answers"]),
  L("73-74", "geometry", "Graphs, Geometry, Shapes and Functions", "Plans and Elevations", "Draw and interpret plans and elevations.", ["Draw 2D views of 3D shapes", "Interpret drawings", "Solve spatial problems"]),
  L("75-76", "geometry", "Graphs, Geometry, Shapes and Functions", "Properties of 3D Shapes", "Understand faces, edges, and vertices of 3D shapes.", ["Identify 3D properties", "Use nets", "Solve 3D problems"]),
  L("77-79", "geometry", "Graphs, Geometry, Shapes and Functions", "Transformations Basics", "Describe and perform basic transformations.", ["Translate shapes", "Reflect shapes", "Rotate shapes"]),
  L("80-81", "geometry", "Graphs, Geometry, Shapes and Functions", "Enlargement", "Perform enlargement with scale factor.", ["Enlarge from a centre", "Use positive and negative scale factors", "Describe enlargements"]),
  L("82-84", "geometry", "Graphs, Geometry, Shapes and Functions", "Combined Transformations", "Combine transformations and describe results.", ["Apply multiple transformations", "Describe combined effects", "Solve transformation problems"]),
  L("85", "geometry", "Graphs, Geometry, Shapes and Functions", "Cylinders", "Calculate surface area and volume of cylinders.", ["Use cylinder formulas", "Solve context problems", "Show working clearly"]),
  L("86", "geometry", "Graphs, Geometry, Shapes and Functions", "Cones", "Calculate surface area and volume of cones.", ["Use cone formulas", "Identify slant height", "Solve problems"]),
  L("87", "geometry", "Graphs, Geometry, Shapes and Functions", "Spheres", "Calculate surface area and volume of spheres.", ["Use sphere formulas", "Apply to real contexts", "Round appropriately"]),
  L("88-89", "equations", "Equations and Inequalities", "Linear Equations", "Solve linear equations in one variable.", ["Solve one-step equations", "Solve multi-step equations", "Check solutions"]),
  L("90-92", "equations", "Equations and Inequalities", "Inequalities", "Solve and represent inequalities.", ["Solve linear inequalities", "Represent on number lines", "Interpret solutions"]),
  L("93", "equations", "Equations and Inequalities", "Simultaneous Equations", "Solve simultaneous equations algebraically and graphically.", ["Use substitution", "Use elimination", "Interpret graphical solutions"]),
  L("100-101", "pythagoras-trig", "Pythagoras Theorem and Trigonometry", "Pythagoras Theorem", "Apply Pythagoras' theorem in right-angled triangles.", ["Identify hypotenuse", "Calculate missing sides", "Verify right-angled triangles"]),
  L("102", "pythagoras-trig", "Pythagoras Theorem and Trigonometry", "Trigonometry in Right Triangles", "Use sin, cos, and tan in right-angled triangles.", ["Choose correct ratio", "Find missing sides", "Find missing angles"]),
  L("103", "statistics", "Statistics", "Types of Data and Sampling", "Differentiate data types and sampling methods.", ["Classify data types", "Describe sampling methods", "Design simple surveys"]),
  L("104", "statistics", "Statistics", "Averages - Mean, Median, Mode", "Calculate and interpret mean, median, and mode.", ["Calculate each average", "Interpret in context", "Choose appropriate average"]),
  L("105", "statistics", "Statistics", "Range", "Calculate and interpret the range.", ["Find the range", "Interpret spread", "Compare data sets"]),
  L("106", "statistics", "Statistics", "Comparing Averages", "Compare averages across data sets.", ["Compare data sets", "Draw conclusions", "Explain choices"]),
  L("107-108", "statistics", "Statistics", "Graphical Representations", "Construct and interpret graphs and charts.", ["Draw appropriate graphs", "Interpret data displays", "Choose suitable representations"]),
];

export const MATHS_Y11 = [
  L("1", "geometry", "Geometry", "Translations", "Translate shapes on a coordinate grid.", ["Translate by a vector", "Describe translations", "Solve translation problems"]),
  L("2", "geometry", "Geometry", "Reflections", "Reflect shapes across given lines.", ["Reflect across lines", "Describe reflections", "Use coordinate rules"]),
  L("3-4", "geometry", "Geometry", "Rotations", "Rotate shapes about a given point.", ["Rotate by given angles", "Describe rotations", "Use centre and angle"]),
  L("5", "geometry", "Geometry", "Enlargement", "Enlarge shapes with a scale factor.", ["Enlarge from a centre", "Use scale factors", "Describe enlargements"]),
  L("6-7", "geometry", "Geometry", "Combined Transformations", "Apply and describe combined transformations.", ["Combine transformations", "Describe results", "Solve problems"]),
  L("8-9", "geometry", "Geometry", "Constructions and Loci", "Perform standard constructions and loci.", ["Construct bisectors", "Draw loci", "Solve construction problems"]),
  L("10", "geometry", "Geometry", "Loci Problems", "Construct and interpret loci in problems.", ["Draw loci accurately", "Interpret conditions", "Solve loci problems"]),
  L("11-14", "geometry", "Geometry", "Bearings", "Understand and use bearings in navigation.", ["Measure bearings", "Solve bearing problems", "Apply with distances"]),
  L("15", "geometry", "Geometry", "Congruence Introduction", "Recognise and prove congruent shapes.", ["Understand congruence", "Use conditions SSS SAS ASA RHS", "Prove congruence"]),
  L("16-17", "geometry", "Geometry", "Similarity", "Recognise and use similarity.", ["Identify similar shapes", "Use scale factors", "Solve similarity problems"]),
  L("18", "geometry", "Geometry", "Geometric Proofs", "Construct geometric proofs involving congruence and similarity.", ["Write logical proofs", "Use geometric reasons", "Solve proof problems"]),
  L("19-21", "geometry", "Geometry", "Vectors", "Understand and use vectors.", ["Add and subtract vectors", "Multiply by a scalar", "Apply vectors in geometry"]),
  L("22", "statistics-probability", "Statistics and Probability", "Probability Language", "Use the language of probability.", ["Use probability vocabulary", "Place events on a scale", "Describe likelihood"]),
  L("23", "statistics-probability", "Statistics and Probability", "Probability of Single Events", "Calculate probability of single events.", ["Use P(A)=favourable/total", "Calculate from scenarios", "Express as fractions and decimals"]),
  L("24", "statistics-probability", "Statistics and Probability", "Probability Notation", "Use probability notation correctly.", ["Use P(A) notation", "Write probabilities clearly", "Interpret notation"]),
  L("25", "statistics-probability", "Statistics and Probability", "Combined Events", "Calculate probabilities of combined events.", ["Use addition rule", "Use multiplication rule", "Solve combined problems"]),
  L("26", "statistics-probability", "Statistics and Probability", "Tree Diagrams", "Use tree diagrams for combined events.", ["Draw tree diagrams", "Calculate along branches", "Solve sequential problems"]),
  L("27", "statistics-probability", "Statistics and Probability", "Venn Diagrams", "Use Venn diagrams for probability.", ["Draw Venn diagrams", "Calculate probabilities", "Solve set problems"]),
  L("29-30", "statistics-probability", "Statistics and Probability", "Plans and Elevations", "Draw and use plans and elevations.", ["Draw 2D views", "Interpret elevations", "Solve spatial problems"]),
  L("31", "statistics-probability", "Statistics and Probability", "Angle Facts", "Apply basic angle facts.", ["Use angles on a line", "Use angles at a point", "Find unknown angles"]),
  L("32", "statistics-probability", "Statistics and Probability", "Parallel Lines Angles", "Use angles with parallel lines and transversals.", ["Identify angle types", "Calculate unknown angles", "Justify answers"]),
  L("33", "statistics-probability", "Statistics and Probability", "Shape Properties", "Apply properties of shapes, parallel lines, and angle facts.", ["Solve angle problems", "Use shape properties", "Reason geometrically"]),
  L("34", "statistics-probability", "Statistics and Probability", "Data Handling", "Collect, represent, and interpret data.", ["Choose representations", "Interpret charts", "Draw conclusions"]),
  L("35", "statistics-probability", "Statistics and Probability", "Statistical Analysis", "Analyse data using statistical measures.", ["Calculate averages and range", "Compare distributions", "Interpret results"]),
  L("36", "graphs-algebra", "Graphs and Algebra", "Rearranging Equations", "Rearrange equations to solve for variables.", ["Rearrange linear equations", "Rearrange with powers", "Use inverse operations"]),
  L("37-38", "graphs-algebra", "Graphs and Algebra", "Cubic and Reciprocal Graphs", "Plot and interpret cubic and reciprocal graphs.", ["Plot cubic functions", "Identify key features", "Interpret graphs"]),
  L("39", "graphs-algebra", "Graphs and Algebra", "Simultaneous Equations Graphically", "Solve simultaneous equations graphically.", ["Plot linear graphs", "Find intersections", "Interpret solutions"]),
  L("40-41", "graphs-algebra", "Graphs and Algebra", "Simultaneous Equations Algebraically", "Solve simultaneous equations algebraically.", ["Use substitution", "Use elimination", "Check solutions"]),
  L("42-43", "graphs-algebra", "Graphs and Algebra", "Expanding Quadratics", "Expand quadratic expressions.", ["Expand single brackets", "Expand double brackets", "Use FOIL method"]),
  L("44-45", "graphs-algebra", "Graphs and Algebra", "Factorising Quadratics", "Factorise quadratic expressions.", ["Factorise simple quadratics", "Factorise with leading coefficient", "Solve by factorising"]),
  L("46-47", "graphs-algebra", "Graphs and Algebra", "Quadratic Graphs", "Plot quadratic graphs and identify key features.", ["Plot parabolas", "Find vertex and roots", "Interpret graphs"]),
  L("48-49", "graphs-algebra", "Graphs and Algebra", "Quadratic Problems", "Solve problems using quadratics.", ["Apply quadratics in context", "Interpret solutions", "Use graphs to solve"]),
  L("50-51", "revision", "Revision Course", "Fractions and Reciprocals", "Revise arithmetic with fractions and reciprocals.", ["Operate with fractions", "Find reciprocals", "Apply in problems"]),
  L("52-72", "revision", "Revision Course", "GCSE Exam Preparation", "Prepare for GCSE Mathematics exams through revision and practice.", ["Review key topics", "Complete mock exams", "Address weaknesses"]),
];

export function allLessons() {
  const rows = [];
  for (const [subject, year, list] of [
    ["english", 10, ENGLISH_Y10],
    ["english", 11, ENGLISH_Y11],
    ["maths", 10, MATHS_Y10],
    ["maths", 11, MATHS_Y11],
  ]) {
    for (const row of list) {
      rows.push({
        subject,
        year,
        examBoard: subject === "english" ? "AQA" : "Edexcel",
        lessonsPerWeek: subject === "english" ? 3 : 2,
        ...row,
      });
    }
  }
  return rows;
}
